# Generated by Django 4.1.1 on 2022-11-09 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam2', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='lNum2',
        ),
    ]
